if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  if (ENABLE_ADDRESS_SANITIZER AND ENABLE_UB_SANITIZER)
      add_compile_options(-fsanitize=address,undefined)
      add_link_options(-fsanitize=address,undefined)
      add_compile_options(-fsanitize-trap=undefined)
      add_link_options(-fsanitize-trap=undefined)
      message(STATUS "Enabled clang address and UB sanitizer")
  elseif (ENABLE_ADDRESS_SANITIZER)
    add_compile_options(-fsanitize=address)
    add_link_options(-fsanitize=address)
    message(STATUS "Enabled clang address sanitizer")
  elseif (ENABLE_UB_SANITIZER)
    add_compile_options(-fsanitize=undefined)
    add_link_options(-fsanitize=undefined)
    message(STATUS "Enabled clang UB sanitizer")
  endif()
else()
  message(WARNING "Sanitizers are supported on clang compiler only! Switch your compiler to clang to enable it")
endif()
